version: "3.8"

services:
  psql-db:
    image: postgres:alpine
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=111
      - POSTGRES_DB=login_system
    ports:
      - '5432:5432'
    volumes:
      - ./new.sql:/docker-entrypoint-initdb.d/new.sql
  reg:
    container_name: reg_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/login_system
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=111
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db